codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80% # Set your desired coverage threshold for the project
    patch:
      default:
        target: 100% # Set your desired coverage threshold for the patch (PR)
