name: wmin-model-dev

channels:
  - conda-forge

dependencies:
  - python >= 3.11
  - mpich
  - lhapdf
  - pandoc
  - mpi4py
  - ultranest
  - pip
  - pip:
    - git+https://${{ secrets.WMIN_TOKEN }}@github.com/HEP-PBSP/colibri.git
